name: Publish Python distributions to TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi  # GitHubの環境名：あとでTestPyPIのTrusted Publisherで登録する名前と合わせる
    permissions:
      id-token: write      # Trusted Publishingに必須

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
